const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "beach",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "city",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "mountain",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "rooms",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    category: "camping",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: "beach",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: "mountain",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: "city",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    category: "mountain",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "camping",
  },
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    category: "city",
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    category: "beach",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    category: "farm",
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Boston",
    country: "United States",
    category: "city",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    category: "beach",
  },
  {
    title: "Mountain View Cabin in Banff",
    description: "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Banff",
    country: "Canada",
    category: "mountain",
  },
  {
    title: "Art Deco Apartment in Miami",
    description: "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Miami",
    country: "United States",
    category: "city",
  },
  {
    title: "Tropical Villa in Phuket",
    description: "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    category: "rooms",
  },
  {
    title: "Historic Castle in Scotland",
    description: "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    category: "rooms",
  },
  {
    title: "Desert Oasis in Dubai",
    description: "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    category: "rooms",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description: "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Montana",
    country: "United States",
    category: "mountain",
  },
  {
    title: "Beachfront Villa in Greece",
    description: "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    category: "beach",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description: "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "camping",
  },
  {
    title: "Historic Cottage in Charleston",
    description: "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Charleston",
    country: "United States",
    category: "farm",
  },
  {
    title: "Modern Apartment in Tokyo",
    description: "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    category: "city",
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description: "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New Hampshire",
    country: "United States",
    category: "mountain",
  },
  {
    title: "Luxury Villa in the Maldives",
    description: "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    category: "beach",
  },
  {
    title: "Ski Chalet in Aspen",
    description: "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Aspen",
    country: "United States",
    category: "mountain",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description: "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "beach",
  },
  {
    title: "Sunset Cliffs House",
    description: "Watch the sun dip below the horizon from the patio of this stunning cliffside beach house.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1688344581936-a91e339e12aa?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U3Vuc2V0JTIwQ2xpZmZzJTIwSG91c2V8ZW58MHx8MHx8fDA%3D",
    },
    price: 2400,
    location: "Santorini",
    country: "Greece",
    category: "beach",
  },
  {
    title: "Sunset Villa in Santorini",
    description: "White-washed walls and blue domes await you in this classic Greek island villa with breathtaking sunset views.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533105079780-92b9be482077?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Oia",
    country: "Greece",
    category: "beach",
  },
  {
    title: "Copacabana Penthouse",
    description: "Experience the vibrant energy of Rio from this luxurious penthouse directly overlooking Copacabana Beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518182170546-07661fd94144?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Rio de Janeiro",
    country: "Brazil",
    category: "beach",
  },
  {
    title: "Thai Beach Hut",
    description: "Simple, serene, and steps from the water. A traditional bamboo hut on a quiet island beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 400,
    location: "Koh Samui",
    country: "Thailand",
    category: "beach",
  },
  {
    title: "Gold Coast Surfer's Pad",
    description: "Modern apartment with rack storage for your boards, located right on the famous Surfers Paradise strip.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1495954484750-af469f2f9be5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Gold Coast",
    country: "Australia",
    category: "beach",
  },
  {
    title: "Hamptons Oceanfront Estate",
    description: "A sprawling estate with private beach access, perfect for large family gatherings and summer vacations.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1669130391362-b202f3cb7755?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8SGFtcHRvbnMlMjBPY2VhbmZyb250JTIwRXN0YXRlfGVufDB8fDB8fHww",
    },
    price: 5500,
    location: "The Hamptons",
    country: "United States",
    category: "beach",
  },
  {
    title: "Swiss Alpine Chalet",
    description: "Classic wooden chalet with a roaring fireplace, located near the best hiking trails in Zermatt.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2100,
    location: "Zermatt",
    country: "Switzerland",
    category: "mountain",
  },
  {
    title: "Rocky Mountain High Cabin",
    description: "Secluded log cabin at high altitude. Enjoy crisp air and star-filled skies in Colorado.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1300,
    location: "Denver",
    country: "United States",
    category: "mountain",
  },
  {
    title: "Patagonia Trekking Base",
    description: "Modern eco-lodge serving as the perfect starting point for your adventures in Torres del Paine.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1692176048096-c28eced57084?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UGF0YWdvbmlhJTIwVHJla2tpbmclMjBCYXNlfGVufDB8fDB8fHww",
    },
    price: 900,
    location: "Patagonia",
    country: "Chile",
    category: "mountain",
  },
  {
    title: "Blue Mountains Cottage",
    description: "Charming cottage surrounded by eucalyptus forests and mist-covered mountains.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 850,
    location: "Katoomba",
    country: "Australia",
    category: "mountain",
  },
  {
    title: "Snowy Hokkaido Lodge",
    description: "Traditional Japanese lodge heavily insulated for the snowy winter, close to Niseko ski slopes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1701310869011-b560f5d75401?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U25vd3klMjBIb2trYWlkbyUyMExvZGdlfGVufDB8fDB8fHww",
    },
    price: 2800,
    location: "Hokkaido",
    country: "Japan",
    category: "mountain",
  },
  {
    title: "Shinjuku Neon Apartment",
    description: "Compact but efficient apartment right in the middle of Tokyo's busiest entertainment district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Tokyo",
    country: "Japan",
    category: "city",
  },
  {
    title: "Parisian Artist Studio",
    description: "Bright and airy studio in Montmartre, formerly used by painters, now a chic rental.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1900,
    location: "Paris",
    country: "France",
    category: "city",
  },
  {
    title: "Chicago Loop Condo",
    description: "High-rise condo with floor-to-ceiling windows overlooking the Chicago River and architecture.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Chicago",
    country: "United States",
    category: "city",
  },
  {
    title: "Singapore Marina Bay Flat",
    description: "Luxury flat with access to an infinity pool and views of the Gardens by the Bay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1599919445953-c604dbd413a0?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U2luZ2Fwb3JlJTIwTWFyaW5hJTIwQmF5JTIwRmxhdHxlbnwwfHwwfHx8MA%3D%3D",
    },
    price: 3100,
    location: "Singapore",
    country: "Singapore",
    category: "city",
  },
  {
    title: "Berlin Kreuzberg Loft",
    description: "Industrial style loft in a converted factory, located in Berlin's trendiest neighborhood.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1522050212171-61b01dd24579?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1400,
    location: "Berlin",
    country: "Germany",
    category: "city",
  },
  {
    title: "Sahara Desert Camp",
    description: "Sleep under a blanket of stars in a luxury tent camp deep in the Sahara dunes.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Merzouga",
    country: "Morocco",
    category: "camping",
  },
  {
    title: "Redwood Forest Yurt",
    description: "A peaceful yurt set among the giant Redwood trees. A magical experience for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 650,
    location: "California",
    country: "United States",
    category: "camping",
  },
  {
    title: "Icelandic Aurora Dome",
    description: "Glass-roofed igloo designed specifically for watching the Northern Lights from bed.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Reykjavik",
    country: "Iceland",
    category: "camping",
  },
  {
    title: "Grand Canyon Glamping",
    description: "Upscale canvas tents located just minutes from the South Rim entrance.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1575552263033-56576fecec6f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8R3JhbmQlMjBDYW55b24lMjBHbGFtcGluZ3xlbnwwfHwwfHx8MA%3D%3D",
    },
    price: 1100,
    location: "Arizona",
    country: "United States",
    category: "camping",
  },
  {
    title: "Rainforest Canopy Tent",
    description: "Suspended tent accommodation in the Costa Rican jungle. Wake up to the sound of monkeys.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1532339142463-fd0a8979791a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 750,
    location: "Monteverde",
    country: "Costa Rica",
    category: "camping",
  },
  {
    title: "Texas Ranch House",
    description: "A sprawling ranch house on a working cattle farm. Horse riding lessons available.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1573208078429-16e423f5f1e3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8VGV4YXMlMjBSYW5jaCUyMEhvdXNlfGVufDB8fDB8fHww",
    },
    price: 1300,
    location: "Austin",
    country: "United States",
    category: "farm",
  },
  {
    title: "French Provence Lavender Farm",
    description: "Stone cottage located in the middle of purple lavender fields. The smell is intoxicating.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1593270525652-1e80adb29d34?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RnJlbmNoJTIwUHJvdmVuY2UlMjBMYXZlbmRlciUyMEZhcm18ZW58MHx8MHx8fDA%3D",
    },
    price: 2400,
    location: "Gordes",
    country: "France",
    category: "farm",
  },
  {
    title: "Vermont Maple Syrup Farm",
    description: "Cozy stay during the fall foliage season or sugaring season in spring.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1595878715977-2e8f8df18ea8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Vermont",
    country: "United States",
    category: "farm",
  },
  {
    title: "Coffee Plantation Stay",
    description: "Stay in the Colombian coffee triangle. Learn how coffee is grown and roasted.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1710612198146-77512950a4b7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Q29mZmVlJTIwUGxhbnRhdGlvbiUyMFN0YXl8ZW58MHx8MHx8fDA%3D",
    },
    price: 600,
    location: "Salento",
    country: "Colombia",
    category: "farm",
  },
  {
    title: "Marrakech Riad",
    description: "Traditional Moroccan house with an interior garden and courtyard. An oasis of calm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1660029713177-a9474780cfde?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TWFycmFrZWNoJTIwUmlhZHxlbnwwfHwwfHx8MA%3D%3D",
    },
    price: 1600,
    location: "Marrakech",
    country: "Morocco",
    category: "rooms",
  },
  {
    title: "English Country Manor Room",
    description: "Rent a wing of a historic English manor house. Afternoon tea included.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Bath",
    country: "United Kingdom",
    category: "rooms",
  },
  {
    title: "Kyoto Machiya Townhouse",
    description: "Stay in a traditional wooden townhouse in the historic Gion district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1742203752336-56b2e9347960?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8S3lvdG8lMjBNYWNoaXlhJTIwVG93bmhvdXNlfGVufDB8fDB8fHww",
    },
    price: 2300,
    location: "Kyoto",
    country: "Japan",
    category: "rooms",
  },
  {
    title: "Underwater Bedroom",
    description: "A once-in-a-lifetime experience sleeping with sharks and fish swimming above you.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578313097818-dfe8d38aa758?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8VW5kZXJ3YXRlciUyMEJlZHJvb218ZW58MHx8MHx8fDA%3D",
    },
    price: 12000,
    location: "Dubai",
    country: "United Arab Emirates",
    category: "rooms",
  }
];

module.exports = { data: sampleListings };